### ISSUE TITLE
Incompatibility with scrbook - tableofcontents entries are indented rightward

### ISSUE THREAD

**Issue by momeni** [vafa/xepersian#1]
In TeXLive 2016, using the xelatex version _3.14159265-2.6-0.99996_, the scrbook version _2016/06/14 v3.21_ document class with **toc=indented** option, the bidi package version _2016/05/23, v19.6_, and the xepersian package version _v16.5, 2016/05/03_, the sections and subsections in the table of contents are indented rightward although the text is rendered from right to left.

Minimal example:
```tex
\documentclass[12pt,a4paper,toc=indented]{scrbook}
\usepackage{xepersian}

\settextfont{XB Niloofar}

\title{testing title}
\author{author name}

\begin{document}

\maketitle
\tableofcontents

\clearpage

\chapter{فصل نخست}
\section{بخش}
بخش اول
\subsection{زیربخش}
زیربخش اول
\section{بخش دوم}
بخش دوم
\chapter{فصل دوم}
\section{بخش اول فصل دوم}
بخش اول فصل دوم

\end{document}
```

**Comment by vafa** [comment]
Thanks for your bug report. I will fix it this week.

**Comment by vafa** [comment]
I pushed version 19.8 of the `bidi` package to CTAN which fixes this issue. If you experience any other issues, please let me know.
