### ISSUE TITLE
column=flexible option of listings package cause weird behavior around period with xepersian

### ISSUE THREAD

**Issue by javadr** [vafa/xepersian#2]
Using xelatex Version 3.14159265-2.6-0.99996 (TeX Live 2016), xepersian ver. 16.6 and bidi ver. 19.7, the listings package will render wrong output around period with columns=flexible option. 
spaceflexible and fullflexibale options also cause such a  problem. 

look at minimal example below:
```
\documentclass{article}
\usepackage{listings}
\usepackage{xepersian}
\settextfont{Yas}

\lstset{basicstyle=\setLTR\ttfamily\small,
    columns=flexible, captiondirection=RTL, }

\begin{document} 
\begin{lstlisting}[caption={کد سلام دنیا با تصویر},label={code1}]  
\documentclass{article}

\begin{document}
    hello worlds
    \includegraphics[height=.1\textheight]{logo}
    7.5
    $2.3$
\end{document}
\end{lstlisting} 
\end{document}
```
when I use above code without columns=flexible option, everything is ok.
I don't discern why it happened?
![selection_031](https://cloud.githubusercontent.com/assets/1178221/18417547/02e89864-7849-11e6-9780-9dc742a31804.png)
!

**Comment by vafa** [comment]
This is expected; simply set the value of `\if@Latin` Boolean to true. That is

````latex
\lstset{basicstyle=\setLTR\@Latintrue\ttfamily\small, ...
````

**Comment by javadr** [comment]
thanks, but in case of using \@Latintrue  this has another unexpected output with captionpos=b option. 

```
\documentclass{book}
\usepackage{listings}

\usepackage{xepersian}
\settextfont{Yas}

\makeatletter\lstset{
basicstyle=\setLTR\@Latintrue\ttfamily\small,
    columns=flexible, 
    captionpos=b,
    captiondirection=RTL, }\makeatother

\begin{document} 
\chapter{one}\section{test}
\chapter{two}\section{test}
\begin{lstlisting}[caption={سلام دنیا},label={code1}]  
\documentclass{article}
\begin{document}
    hello worlds
\end{document}
\end{lstlisting} 
\end{document}
```
![image](https://cloud.githubusercontent.com/assets/1178221/18421623/b922c2b2-78a3-11e6-8ea8-7f799656e2e5.png)

while with captionpos=t there is no problem:
![image](https://cloud.githubusercontent.com/assets/1178221/18421630/e6cd720c-78a3-11e6-9056-e48db48d237e.png)

in my case, this problem will be solved with `\bidi@appto\lstlistingname{\setLTR\@Latinfalse}` but I want to know why caption position has side effect on the caption output?

**Comment by vafa** [comment]
> but I want to know why caption's position has side effect on the caption output?

Is not this obvious? when you put caption on the top, your verbatim comes after caption so changing the value of the Boolean for verbatim does not effect caption. However, when the caption is placed after verbatim, the value of the Boolean also effects caption.

Anyway, I do not like this inconsistent behavior so I have made some substantial changes in both `bidi` and `xepersian` packages. There is now a new `captionscript` key which has two values `latin` and `nonlatin`. I am planning to upload the new version of both packages next month but until then you can use the GitHub version. Simply running `makectanzip` script in each of the packages gives you TDS which is easy to install. 

I also have changed the `\if@Latin` Boolean to `\if@nonlatin` so the logic is now reversed (more simplified). Your minimal example can be changed for the new version of packages as follows

````latex
\documentclass{book}
\usepackage{listings}

\usepackage{xepersian}
\settextfont{Yas}

\makeatletter
\lstset{
basicstyle=\setLTR\@nonlatinfalse\ttfamily\small,
    columns=flexible, 
    captionpos=b,
    captiondirection=RTL,captionscript=nonlatin}
    \makeatother

\begin{document} 
\chapter{one}\section{test}
\chapter{two}\section{test}
\begin{lstlisting}[caption={سلام دنیا},label={code1}]  
\documentclass{article}
\begin{document}
 hello worlds
    \includegraphics[height=.1\textheight]{logo}
    7.5
    $2.3$
\end{document}
\end{lstlisting} 
\end{document}
````

For this to work, **you need the new versions of both `bidi` and `xepersian` packages**.

**Comment by javadr** [comment]
thanks for updates, but it seems you've forgotten to use this option in userguide! see the pictures below:
![image](https://cloud.githubusercontent.com/assets/1178221/18606910/6c311f20-7cd2-11e6-9af2-d7b84f0be2a4.png)
![image](https://cloud.githubusercontent.com/assets/1178221/18606922/816ae10a-7cd2-11e6-8e99-b2d50e7a79bd.png)
![image](https://cloud.githubusercontent.com/assets/1178221/18606926/af3408f0-7cd2-11e6-9c13-543474b9859c.png)
![image](https://cloud.githubusercontent.com/assets/1178221/18606929/d321b942-7cd2-11e6-88ae-ce1cf6a35ff2.png)

and so on.

**Comment by vafa** [comment]
See #5 .
