### ISSUE TITLE
spelling error in version 16.8 documentation (16.8 -> 8.16)

### ISSUE THREAD

**Issue by hadi-safi-aghdam** [vafa/xepersian#5]
hello vafa
There is a "spelling error" in "version 16.8 of xepersian documantation".
The 16.8 was typed (8.16) incorrectly.
also, in page 4, in section:
2 . 1 XePersian Info On Th Terminal and In Th Log File
`* v168 . , 2016/09/15`
Very thanks for the supporting of xepersian.
Best wishes.
![16 8](https://cloud.githubusercontent.com/assets/4012764/18589387/c4bf0aaa-7c3f-11e6-87d3-47a4d111aa4d.jpg)

**Comment by vafa** [comment]
There is no spelling error; this is simply due to the fact that I forgot to use the new version of the `bidi` package when I was typesetting the documentation at the time of submission. This will be automatically fixed in the next version.
