### ISSUE TITLE
new xepersian (v16.8) typesets decimal point numbers as nonlatin!

### ISSUE THREAD

**Issue by javadr** [vafa/xepersian#6]
I'm so confused why new version of xepersian package typesets decimal point numbers in nonlatin mode! before this update every thing worked fine!

```latex
\documentclass{article}

\usepackage{xepersian}
\settextfont{Yas}

\begin{document}

1.2

\xepersianversion

\makeatletter\@nonlatinfalse
\xepersianversion
\makeatother

\end{document}
```

![selection_031](https://cloud.githubusercontent.com/assets/1178221/18613276/85d97412-7d8c-11e6-872d-40a4b59bb90e.png)

**Comment by vafa** [comment]
To be honest, I do not see any issues here. I have not changed anything really. Therefore, I consider this invalid.
